<?php

// Add Search Function
add_theme_support( 'html5', array( 'search-form' ) );

// Register Custom Menus
  register_nav_menus( array(
    'header-menu' => 'Header Menu',
    'footer-menu' => 'Footer Menu',
    'alt-menu' => 'Alt Menu'
  ) );

 // Register custom navigation walker
    require_once('wp_bootstrap_navwalker.php');

// Remove admin bar on front 
// show_admin_bar(false);

// Add Featured post image 
add_theme_support( 'post-thumbnails' ); 


//Hide Advanced Custom Fields menu item from the admin menu from non-specific admins
function remove_acf_menu()
{
    // provide a list of usernames who can edit custom field definitions here
    $admins = array(
        'cfwiemployee'
    );
    // get the current user
    $current_user = wp_get_current_user();

    // match and remove if needed
    if( !in_array( $current_user->user_login, $admins ) )
    {
        remove_menu_page('edit.php?post_type=acf');
    }
}
add_action( 'admin_menu', 'remove_acf_menu', 999 );


// Order Pages in Admin alphabetically
function set_post_order_in_admin( $wp_query ) {
global $pagenow;
  if ( is_admin() && 'edit.php' == $pagenow && !isset($_GET['orderby'])) {
    $wp_query->set( 'orderby', 'title' );
    $wp_query->set( 'order', 'ASC' );
  }
}
add_filter('pre_get_posts', 'set_post_order_in_admin' );


// Remove Dashboard Admin Menu Items
function remove_menus () {
global $menu;
$restricted = array(__('Media'),__('PostsX'),__('Tools'),__('Flamingo'),__('SettingsX'),__('Plugins'), __('Links'), __('Comments'),__('AppearanceX'));
end ($menu);
while (prev($menu)){
$value = explode(' ',$menu[key($menu)][0]);
if(in_array($value[0] != NULL?$value[0]:"" ,$restricted)){unset($menu[key($menu)]);}
}
}
add_action('admin_menu', 'remove_menus');


//Remove Cluttered Dashboard Widgets and Boxes
function remove_dashboard_meta() {
        remove_meta_box( 'dashboard_incoming_links', 'dashboard', 'normal' );
        remove_meta_box( 'dashboard_plugins', 'dashboard', 'normal' );
        remove_meta_box( 'dashboard_primary', 'dashboard', 'normal' );
        remove_meta_box( 'dashboard_secondary', 'dashboard', 'normal' );
        remove_meta_box( 'dashboard_incoming_links', 'dashboard', 'normal' );
        remove_meta_box( 'dashboard_quick_press', 'dashboard', 'side' );
        remove_meta_box( 'dashboard_recent_drafts', 'dashboard', 'side' );
        remove_meta_box( 'dashboard_recent_comments', 'dashboard', 'normal' );
        remove_meta_box( 'dashboard_right_now', 'dashboard', 'normal' );
}
add_action( 'admin_init', 'remove_dashboard_meta' );

// Clean up header bloat generated by wordpress on front end
remove_action( 'wp_head', 'feed_links_extra'); // Display the links to the extra feeds such as category feeds
remove_action( 'wp_head', 'feed_links'); // Display the links to the general feeds: Post and Comment Feed
remove_action( 'wp_head', 'rsd_link'); // Display the link to the Really Simple Discovery service endpoint, EditURI link
remove_action( 'wp_head', 'wlwmanifest_link' ); // Display the link to the Windows Live Writer manifest file.
remove_action( 'wp_head', 'index_rel_link' ); // index link
remove_action( 'wp_head', 'parent_post_rel_link', 10); // prev link
remove_action( 'wp_head', 'start_post_rel_link', 10); // start link
remove_action( 'wp_head', 'adjacent_posts_rel_link_wp_head', 10); // Display relational links for the posts adjacent to the current post.
remove_action( 'wp_head', 'wp_generator'); // Display the XHTML generator that is generated on the wp_head hook, WP version

// Remove Theme Editor Menu
 function remove_editor_menu() {
  remove_action('admin_menu', '_add_themes_utility_last', 101);
 }
 add_action('_admin_menu', 'remove_editor_menu', 1);

// Add url shortcode
function url_shortcode() {
return get_bloginfo('url');
}
add_shortcode('url','url_shortcode');


// Register Widget Area For Sidebar
function digitus_widgets_init() {

    register_sidebar( array(
        'name' => 'Header',
        'id' => 'header',
        'before_widget' => '',
        'after_widget' => '',
        'before_title' => '',
        'after_title' => '',
    ) );
}
add_action( 'widgets_init', 'digitus_widgets_init' );

// Register Sidebar(s)
if ( function_exists('register_sidebar') ) {

    register_sidebar(array(
      'name' => 'Blog Sidebar',
      'description' => '',
      'before_widget' => '<li><div class="panel panel-default">',
      'before_title' => '<div class="panel-heading"><h3 class="panel-title">',
      'after_title' => '</h3></div><div class="panel-body">',
      'after_widget' => '</div></div></li>'
    ));
    
    register_sidebar(array(
      'name' => 'Page Sidebar',
      'description' => '',
      'before_widget' => '<li><div class="panel panel-default">',
      'before_title' => '<div class="panel-heading"><h3 class="panel-title">',
      'after_title' => '</h3></div><div class="panel-body">',
      'after_widget' => '</div></div></li>'
    ));

}

// Remove CPT UI from Admin Menu
// function remove_cpt_menu() {
//	remove_menu_page( 'cptui_main_menu' );
// }
// add_action( 'admin_menu', 'remove_cpt_menu' );



?>